# By Stephen Harrison
# GUI generated by PAGE

# This file is used to start the program

import os
import sys
import threading

try:
    import Tkinter as tk
    from Tkinter import filedialog
except ImportError:
    import tkinter as tk
    from tkinter import filedialog
    
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from GUI_support import *

# Called to launch GUI
def vp_start_gui():
    global w, root
    root = tk.Tk()
    set_Tk_var()
    top = Toplevel1 (root)
    init(root, top)
    root.mainloop()

w = None

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

# Contains top form
class Toplevel1:
    def __init__(self, top=None):

        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("410x370+442+278")
        top.minsize(120, 1)
        top.maxsize(2564, 2501)
        top.resizable(1,  1)
        top.title("Bulk Phone Updater")
        top.configure(background="#c0c0c0")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        # Button to browse for primary file
        self.ButtonPrimaryFile = tk.Button(top)
        self.ButtonPrimaryFile.place(relx=0.024, rely=0.216, height=24, width=87)
        self.ButtonPrimaryFile.configure(activebackground="#ececec")
        self.ButtonPrimaryFile.configure(activeforeground="#000000")
        self.ButtonPrimaryFile.configure(background="#d9d9d9")
        self.ButtonPrimaryFile.configure(command=lambda: PrimaryFile.ComboboxUpdate(self, self.TextBoxPrimaryFile,
                                                            self.ComboboxPriFileName, self.ComboboxPriFilePhone))
        self.ButtonPrimaryFile.configure(disabledforeground="#a3a3a3")
        self.ButtonPrimaryFile.configure(foreground="#000000")
        self.ButtonPrimaryFile.configure(highlightbackground="#d9d9d9")
        self.ButtonPrimaryFile.configure(highlightcolor="black")
        self.ButtonPrimaryFile.configure(pady="0")
        self.ButtonPrimaryFile.configure(relief="groove")
        self.ButtonPrimaryFile.configure(text='''Primary File''')

        self.TextBoxPrimaryFile = tk.Text(top)
        self.TextBoxPrimaryFile.place(relx=0.244, rely=0.216, relheight=0.068, relwidth=0.741)
        self.TextBoxPrimaryFile.configure(background="white")
        self.TextBoxPrimaryFile.configure(font="TkTextFont")
        self.TextBoxPrimaryFile.configure(foreground="black")
        self.TextBoxPrimaryFile.configure(highlightbackground="#d9d9d9")
        self.TextBoxPrimaryFile.configure(highlightcolor="black")
        self.TextBoxPrimaryFile.configure(insertbackground="black")
        self.TextBoxPrimaryFile.configure(selectbackground="blue")
        self.TextBoxPrimaryFile.configure(selectforeground="white")
        self.TextBoxPrimaryFile.configure(wrap="none")

        self.TextBoxNewInfoFile = tk.Text(top)
        self.TextBoxNewInfoFile.place(relx=0.244, rely=0.324, relheight=0.068, relwidth=0.741)
        self.TextBoxNewInfoFile.configure(background="white")
        self.TextBoxNewInfoFile.configure(font="TkTextFont")
        self.TextBoxNewInfoFile.configure(foreground="black")
        self.TextBoxNewInfoFile.configure(highlightbackground="#d9d9d9")
        self.TextBoxNewInfoFile.configure(highlightcolor="black")
        self.TextBoxNewInfoFile.configure(insertbackground="black")
        self.TextBoxNewInfoFile.configure(selectbackground="blue")
        self.TextBoxNewInfoFile.configure(selectforeground="white")
        self.TextBoxNewInfoFile.configure(wrap="none")


        # Button to browse for new info file
        self.ButtonNewInfoFile = tk.Button(top)
        self.ButtonNewInfoFile.place(relx=0.024, rely=0.324, height=24, width=87)
        self.ButtonNewInfoFile.configure(activebackground="#ececec")
        self.ButtonNewInfoFile.configure(activeforeground="#000000")
        self.ButtonNewInfoFile.configure(background="#d9d9d9")
        self.ButtonNewInfoFile.configure(command=lambda: NewFile.ComboboxUpdate(self,self.TextBoxNewInfoFile, 
                                                            self.ComboboxNewInfoName, self.ComboboxNewInfoFilePhone))
        self.ButtonNewInfoFile.configure(disabledforeground="#a3a3a3")
        self.ButtonNewInfoFile.configure(foreground="#000000")
        self.ButtonNewInfoFile.configure(highlightbackground="#d9d9d9")
        self.ButtonNewInfoFile.configure(highlightcolor="black")
        self.ButtonNewInfoFile.configure(pady="0")
        self.ButtonNewInfoFile.configure(relief="groove")
        self.ButtonNewInfoFile.configure(text='''New Info File''')

        self.FrameSettings = tk.Frame(top)
        self.FrameSettings.place(relx=0.073, rely=0.432, relheight=0.43, relwidth=0.841)
        self.FrameSettings.configure(relief='groove')
        self.FrameSettings.configure(borderwidth="2")
        self.FrameSettings.configure(relief="groove")
        self.FrameSettings.configure(background="#d9d9d9")
        self.FrameSettings.configure(highlightbackground="#d9d9d9")
        self.FrameSettings.configure(highlightcolor="black")

        self.ComboboxPriFileName = ttk.Combobox(self.FrameSettings)
        self.ComboboxPriFileName.place(relx=0.591, rely=0.321, relheight=0.126, relwidth=0.235)

        self.LabelPriFilePhone = tk.Label(self.FrameSettings)
        self.LabelPriFilePhone.place(relx=0.058, rely=0.195, height=18, width=150)
        self.LabelPriFilePhone.configure(activebackground="#f9f9f9")
        self.LabelPriFilePhone.configure(activeforeground="black")
        self.LabelPriFilePhone.configure(anchor='w')
        self.LabelPriFilePhone.configure(background="#d9d9d9")
        self.LabelPriFilePhone.configure(cursor="fleur")
        self.LabelPriFilePhone.configure(disabledforeground="#a3a3a3")
        self.LabelPriFilePhone.configure(foreground="#000000")
        self.LabelPriFilePhone.configure(highlightbackground="#d9d9d9")
        self.LabelPriFilePhone.configure(highlightcolor="black")
        self.LabelPriFilePhone.configure(justify='left')
        self.LabelPriFilePhone.configure(text='''Primary File Phone Column''')

        self.LabelPriFileName = tk.Label(self.FrameSettings)
        self.LabelPriFileName.place(relx=0.055, rely=0.321, height=18, width=150)

        self.LabelPriFileName.configure(activebackground="#f9f9f9")
        self.LabelPriFileName.configure(activeforeground="black")
        self.LabelPriFileName.configure(anchor='w')
        self.LabelPriFileName.configure(background="#d9d9d9")
        self.LabelPriFileName.configure(disabledforeground="#a3a3a3")
        self.LabelPriFileName.configure(foreground="#000000")
        self.LabelPriFileName.configure(highlightbackground="#d9d9d9")
        self.LabelPriFileName.configure(highlightcolor="black")
        self.LabelPriFileName.configure(justify='left')
        self.LabelPriFileName.configure(text='''Primary File Name Column''')

        self.LabelNewInfoFilePhone = tk.Label(self.FrameSettings)
        self.LabelNewInfoFilePhone.place(relx=0.055, rely=0.579, height=18, width=140)
        self.LabelNewInfoFilePhone.configure(activebackground="#f9f9f9")
        self.LabelNewInfoFilePhone.configure(activeforeground="black")
        self.LabelNewInfoFilePhone.configure(anchor='w')
        self.LabelNewInfoFilePhone.configure(background="#d9d9d9")
        self.LabelNewInfoFilePhone.configure(disabledforeground="#a3a3a3")
        self.LabelNewInfoFilePhone.configure(foreground="#000000")
        self.LabelNewInfoFilePhone.configure(highlightbackground="#d9d9d9")
        self.LabelNewInfoFilePhone.configure(highlightcolor="black")
        self.LabelNewInfoFilePhone.configure(text='''New Info Phone Column''')

        self.LabelNewInfoName = tk.Label(self.FrameSettings)
        self.LabelNewInfoName.place(relx=0.055, rely=0.711, height=18, width=130)

        self.LabelNewInfoName.configure(activebackground="#f9f9f9")
        self.LabelNewInfoName.configure(activeforeground="black")
        self.LabelNewInfoName.configure(anchor='w')
        self.LabelNewInfoName.configure(background="#d9d9d9")
        self.LabelNewInfoName.configure(disabledforeground="#a3a3a3")
        self.LabelNewInfoName.configure(foreground="#000000")
        self.LabelNewInfoName.configure(highlightbackground="#d9d9d9")
        self.LabelNewInfoName.configure(highlightcolor="black")
        self.LabelNewInfoName.configure(text='''New Info Name Column''')

        self.ComboboxNewInfoFilePhone = ttk.Combobox(self.FrameSettings)
        self.ComboboxNewInfoFilePhone.place(relx=0.591, rely=0.579, relheight=0.126, relwidth=0.235)

        self.ComboboxNewInfoName = ttk.Combobox(self.FrameSettings)
        self.ComboboxNewInfoName.place(relx=0.591, rely=0.711, relheight=0.119, relwidth=0.235)

        self.ComboboxPriFilePhone = ttk.Combobox(self.FrameSettings)
        self.ComboboxPriFilePhone.place(relx=0.591, rely=0.195, relheight=0.119, relwidth=0.235)


        self.Progressbar = ttk.Progressbar(top)
        self.Progressbar.place(relx=0.073, rely=0.892, relwidth=0.561, relheight=0.0, height=22)
        self.Progressbar.configure(length="230", mode='determinate')

        #Thread for run function
        def threadbringer(self):
            thread_run = threading.Thread(target=RunEvent.ButtonRun_Click, args=[self, self.ComboboxPriFileName.get(),
                                            self.ComboboxPriFilePhone.get(), self.ComboboxNewInfoName.get(),
                                            self.ComboboxNewInfoFilePhone.get(), self.Progressbar])
            thread_run.daemon = True
            thread_run.start()

        # Button for run function
        self.ButtonRun = tk.Button(top)
        self.ButtonRun.place(relx=0.659, rely=0.892, height=24, width=107)
        self.ButtonRun.configure(activebackground="#ececec")
        self.ButtonRun.configure(activeforeground="#000000")
        self.ButtonRun.configure(background="#d9d9d9")
        self.ButtonRun.configure(command=lambda: threadbringer(self))
        self.ButtonRun.configure(cursor="fleur")
        self.ButtonRun.configure(disabledforeground="#a3a3a3")
        self.ButtonRun.configure(foreground="#000000")
        self.ButtonRun.configure(highlightbackground="#d9d9d9")
        self.ButtonRun.configure(highlightcolor="black")
        self.ButtonRun.configure(pady="0")
        self.ButtonRun.configure(text='''Run''')

        self.Info = tk.Label(top)
        self.Info.place(relx=0.024, rely=0.027, height=63, width=394)
        self.Info.configure(background="#d9d9d9")
        self.Info.configure(disabledforeground="#a3a3a3")
        self.Info.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Info.configure(foreground="#000000")
        self.Info.configure(text='''Files must have headers''')
        self.Info.configure(wraplength="280")

if __name__ == '__main__':
    vp_start_gui()